name: Generation
on:
  push:
    paths:
      - 'docs/**'
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "http://57.128.18.151:8000/generate?file=moi.json"
          method: 'PUT'
          timeout: 120000
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
          echo ${{ steps.myRequest.outputs.headers }}
